name: Deploy PlaneMap API
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html/PlaneMap-API
            git reset --hard
            git pull origin main
            npm install
            pm2 restart PlaneMap-API
